# Ruff configuration file for Python analysis
line-length = 120
indent-width = 4

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort (import sorting)
    "C90", # mccabe complexity checks
    "B",   # flake8-bugbear
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
